### GeoJSON endpoints for geojson.io visualization

### 1. Obtenir tous les bacs en GeoJSON
@baseUrl = http://localhost:3000/api/v1
@contentType = application/json
GET {{baseUrl}}/geo/bins
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNDg3YjVjYy0xZGY0LTQ2NTAtYTFmNy1hNzk5ODU5YmUyMjEiLCJlbWFpbCI6Imxvb25hNzc1N0BnbWFpbC5jb20iLCJwaG9uZSI6IisyMzc2OTg3NjU0MzIiLCJyb2xlIjoiQ0lUSVpFTiIsImlhdCI6MTc3NTE1MjAzMiwiZXhwIjoxNzc2OTY2NDMyfQ.GYvjivWe67Uv7KnRZXSMFDQXxQO2dec5g-orlew0FGo
### 2. Obtenir tous les quartiers en GeoJSON
GET {{baseUrl}}/geo/neighborhoods
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDY5ZjA4MS04NmUwLTRmMDktODU4NS0yYjRhNzQyNmEzNGYiLCJlbWFpbCI6ImFwb2xsaW5lYmFuZW1iQGdtYWlsLmNvbSIsInBob25lIjoiKzIzNzY5ODc2NTQzMiIsInJvbGUiOiJDSVRJWkVOIiwiaWF0IjoxNzczODUxNjMwLCJleHAiOjE3NzU2NjYwMzB9.x--KmGSpowXTokIvNG_nSd0OcURXudJ_waqrKQ6RsIc

### 3. Obtenir tout (bacs + quartiers) en GeoJSON
GET {{baseUrl}}/geo/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDY5ZjA4MS04NmUwLTRmMDktODU4NS0yYjRhNzQyNmEzNGYiLCJlbWFpbCI6ImFwb2xsaW5lYmFuZW1iQGdtYWlsLmNvbSIsInBob25lIjoiKzIzNzY5ODc2NTQzMiIsInJvbGUiOiJDSVRJWkVOIiwiaWF0IjoxNzczODQ1ODQzLCJleHAiOjE3NzU2NjAyNDN9.yZ5L1pOrC3MPcArBDbdL7aNavqMpSRUlIKOPUbrH24I

