### Version SANS photo (plus simple)

@baseUrl = http://localhost:3000
@contentType = application/json

POST {{baseUrl}}/reports
Content-Type: {{contentType}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDY5ZjA4MS04NmUwLTRmMDktODU4NS0yYjRhNzQyNmEzNGYiLCJlbWFpbCI6ImFwb2xsaW5lYmFuZW1iQGdtYWlsLmNvbSIsInBob25lIjoiKzIzNzY5ODc2NTQzMiIsInJvbGUiOiJDSVRJWkVOIiwiaWF0IjoxNzczOTkyODA4LCJleHAiOjE3NzU4MDcyMDh9.jlnbYyNPdjObt3eQk9WhsemxQ_bfonmEcfkBb1sudBA

{
  "bacId": "0433bb58-16dd-4252-a742-e4cabf9808bf",
  "reportType": "FULL", 
  "description": "Le bac est plein et déborde",
  "priority": "HIGH"
}
